Repository tkeel-io/cli, pull requests merged in 2021-12, with the labels that each got.

#70 Feat e2e
  .github/workflows/main.yml
  OWNERS
Labels: needs-ok-to-test, size/S

#73 feat: invoke use portforward
  cmd/invoke.go
  pkg/kubernetes/helm.go
  pkg/kubernetes/invoke.go
  pkg/kubernetes/plugin.go
  pkg/kubernetes/pods.go
  pkg/kubernetes/portforward.go
  pkg/kubernetes/uninstall.go
Labels: needs-ok-to-test, approved, size/L

#75 chore: PR and iisues temp
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/pull_request_template.md
Labels: size/M, ok-to-test, lgtm, approved

#72 feat: add some e2e cases
  tests/e2e/src/cases/cli.case.ts
  tests/e2e/src/cases/cli.test.ts
  tests/e2e/src/core.d.ts
Labels: ok-to-test, lgtm, size/L

#77 fix: lint
  pkg/kubernetes/invoke.go
  pkg/kubernetes/pods.go
  pkg/kubernetes/portforward.go
Labels: size/M, needs-ok-to-test, approved, kind/neet-to-verify

#49 feat: Optimising repo interceptions
  cmd/plugin/install.go
  cmd/plugin/install_test.go
Labels: enhancement, size/M, needs-ok-to-test, lgtm, approved
