Repository tkeel-io/cli, pull requests merged in 2022-03, with the labels that each got.

#105 fix custom tkeel repo url;
  pkg/kubernetes/kubernetes.go
Labels: size/M, needs-ok-to-test

#106 fix get dapr version
  pkg/kubernetes/check.go
Labels: needs-ok-to-test, size/S

#107 feat: save install config to configmap
  cmd/init.go
  cmd/plugin/install.go
  cmd/plugin/show.go
  cmd/tkeel.go
  cmd/uninstall.go
  go.mod
  go.sum
  pkg/kubernetes/helm.go
  pkg/kubernetes/installer.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/plugin.go
  pkg/kubernetes/repo.go
  pkg/kubernetes/rudder.go
  pkg/kubernetes/tenant.go
  pkg/kubernetes/user.go
Labels: needs-ok-to-test, size/L

#109 fix install config default value
  cmd/init.go
  cmd/tkeel.go
  cmd/uninstall.go
  pkg/kubernetes/kubernetes.go
Labels: size/M, needs-ok-to-test

#110 fix: dynamic namespace
  pkg/kubernetes/kubernetes.go
Labels: size/XS, needs-ok-to-test

#111 fix: golangci-lint format
  .golangci.yaml
  cmd/config.go
  cmd/init.go
  cmd/installer/installer.go
  cmd/installer/show.go
  cmd/installer/types.go
  cmd/plugin/disable.go
  cmd/plugin/enable.go
  cmd/tenant/delete.go
  cmd/tenant/show.go
  cmd/user/create.go
  cmd/user/delete.go
  cmd/user/show.go
  cmd/user/types.go
  cmd/user/user.go
  fileutil/util_test.go
  pkg/kubernetes/core.go
  pkg/kubernetes/helm.go
  pkg/kubernetes/installer.go
  pkg/kubernetes/invoke.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/plugin.go
  pkg/kubernetes/repo.go
  pkg/kubernetes/tenant.go
  pkg/kubernetes/user.go
Labels: needs-ok-to-test, size/L

#114 fix: dump config.yaml error
  fileutil/util.go
  fileutil/util_test.go
  pkg/kubernetes/kubernetes.go
Labels: needs-ok-to-test, size/S

#117 fix:cli init
  Jenkinsfile
Labels: needs-ok-to-test

#122 feat: init add plugins
  cmd/config.go
  cmd/plugin/install.go
  cmd/plugin/list.go
  cmd/uninstall.go
  fileutil/util.go
  go.mod
  go.sum
  pkg/kubernetes/common.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/plugin.go
  pkg/kubernetes/rudder.go
  pkg/kubernetes/uninstall.go
  pkg/utils/utils.go
Labels: needs-ok-to-test, size/L

#124 Feat/plugins
  .github/workflows/main.yml
  .github/workflows/release.yml
  cmd/plugin/enable.go
  cmd/plugin/install_test.go
  cmd/plugin/types.go
  cmd/tenant/create.go
  cmd/tenant/delete.go
  cmd/tenant/list.go
  cmd/tenant/show.go
  cmd/tenant/tenant.go
  cmd/upgrade.go
  cmd/user/create.go
  cmd/user/delete.go
  cmd/user/list.go
  cmd/user/show.go
  cmd/user/user.go
  pkg/kubernetes/common.go
  pkg/kubernetes/helm.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/uninstall.go
Labels: needs-ok-to-test, size/L

#125 feat: add register command
  cmd/plugin/register.go
  fileutil/util_test.go
  pkg/kubernetes/plugin.go
  pkg/utils/utils_test.go
Labels: needs-ok-to-test, size/L
