Repository tkeel-io/cli, pull requests merged in 2022-01, with the labels that each got.

#81 feat: add core command
  cmd/core/apply.go
  cmd/core/core.go
  cmd/core/create.go
  cmd/core/get.go
  cmd/tkeel.go
  go.mod
  go.sum
  pkg/kubernetes/core.go
  pkg/kubernetes/invoke.go
Labels: needs-ok-to-test, approved, size/L

#87 feat: add invoke test & refactor
  go.mod
  go.sum
  pkg/errutil/check.go
  pkg/errutil/check_test.go
  pkg/kubernetes/invoke.go
  pkg/kubernetes/invoke_test.go
  pkg/kubernetes/plugin.go
  pkg/kubernetes/pods.go
  pkg/kubernetes/portforward.go
  pkg/kubernetes/tenant.go
  pkg/kubernetes/testutils.go
Labels: needs-ok-to-test, approved, size/XL

#89 fix: remove unuse file
  pkg/kubernetes/testutils.go
Labels: size/M, needs-ok-to-test, approved

#88 feat: update
  .github/pull_request_template.md
Labels: size/XS, needs-ok-to-test, approved

#86 refactor: get portforward method
  go.sum
  pkg/kubernetes/invoke.go
  pkg/kubernetes/invoke_test.go
  pkg/kubernetes/pods.go
  pkg/kubernetes/portforward.go
Labels: needs-ok-to-test, size/L

#84 Feat: admin login command
  README.md
  README_zh.md
  cmd/admin/admin.go
  cmd/admin/login.go
  cmd/tkeel.go
  fileutil/util.go
  fileutil/util_test.go
  go.mod
  go.sum
  pkg/kubernetes/rudder.go
Labels: needs-ok-to-test, size/XXL

#90 FIX Plugin Command and ADD Repo Command
  cmd/plugin/install.go
  cmd/plugin/install_test.go
  cmd/plugin/list.go
  cmd/plugin/plugin.go
  cmd/plugin/uninstall.go
  cmd/repo/add.go
  cmd/repo/delete.go
  cmd/repo/list.go
  cmd/repo/repo.go
  cmd/tkeel.go
  fileutil/util.go
  fmtutil/utils.go
  go.mod
  go.sum
  pkg/kubernetes/plugin.go
  pkg/kubernetes/repo.go
Labels: needs-ok-to-test, size/L

#91 fix: plugin register and unregister
  cmd/plugin/install.go
  cmd/plugin/register.go
  cmd/plugin/unregister.go
  pkg/kubernetes/plugin.go
Labels: size/M, needs-ok-to-test

#92 fix: term.ReadPassword not work in Windows
  cmd/admin/login.go
  cmd/plugin/register.go
Labels: size/XS, needs-ok-to-test

#93 refator: password input use pkg survey
  cmd/admin/login.go
  cmd/plugin/register.go
  go.mod
  go.sum
Labels: size/M, needs-ok-to-test

#95 fix: fixed plugin install --config file read
  cmd/plugin/install.go
  pkg/kubernetes/plugin.go
Labels: needs-ok-to-test, size/S

#96 Fix/plugin
  cmd/plugin/install.go
  cmd/tkeel.go
  fileutil/util.go
Labels: size/M, needs-ok-to-test
